<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Attendance Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2c3e50;
        }
        .header p {
            margin: 5px 0 0;
            font-size: 14px;
            color: #7f8c8d;
        }
        .filters {
            margin-bottom: 15px;
            padding: 10px;
            background-color: #f8f9fa;
            border-radius: 4px;
        }
        .filters p {
            margin: 5px 0;
            font-weight: bold;
        }
        .filters ul {
            margin: 5px 0;
            padding-left: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            color: #7f8c8d;
            border-top: 1px solid #ddd;
            padding-top: 5px;
        }
        .status-present { color: #27ae60; }
        .status-absent { color: #e74c3c; }
        .status-late { color: #f39c12; }
        .status-on-leave { color: #9b59b6; }
        .status-half-day { color: #3498db; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Attendance Report</h1>
        <p>Generated on: {{ $date }}</p>
    </div>

    @if(count($filters) > 0)
    <div class="filters">
        <p>Filters Applied:</p>
        <ul>
            @foreach($filters as $filter)
                <li>{{ $filter }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Employee ID</th>
                <th>Employee Name</th>
                <th>Department</th>
                <th>Designation</th>
                <th>Date</th>
                <th>Day</th>
                <th>Check In</th>
                <th>Check Out</th>
                <th>Status</th>
                <th>Working Hours</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @forelse($attendances as $index => $attendance)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $attendance->employee->employee_id ?? 'N/A' }}</td>
                    <td>{{ $attendance->employee->user->name ?? 'N/A' }}</td>
                    <td>{{ $attendance->employee->department->name ?? 'N/A' }}</td>
                    <td>{{ $attendance->employee->designation->title ?? 'N/A' }}</td>
                    <td>{{ $attendance->date->format('d-m-Y') }}</td>
                    <td>{{ $attendance->date->format('l') }}</td>
                    <td>{{ $attendance->check_in ? \Carbon\Carbon::parse($attendance->check_in)->format('h:i A') : 'N/A' }}</td>
                    <td>{{ $attendance->check_out ? \Carbon\Carbon::parse($attendance->check_out)->format('h:i A') : 'N/A' }}</td>
                    <td class="status-{{ strtolower(str_replace(' ', '-', $attendance->status)) }}">
                        {{ $attendance->status }}
                    </td>
                    <td>
                        @if($attendance->check_in && $attendance->check_out)
                            @php
                                $start = \Carbon\Carbon::parse($attendance->check_in);
                                $end = \Carbon\Carbon::parse($attendance->check_out);
                                $hours = $end->diffInMinutes($start) / 60;
                            @endphp
                            {{ number_format($hours, 2) }} hrs
                        @else
                            N/A
                        @endif
                    </td>
                    <td>{{ $attendance->remarks ?? 'N/A' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="12" style="text-align: center;">No attendance records found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by PayNinja HRM | {{ config('app.name') }}</p>
    </div>
</body>
</html>
